---
abstract: 'Dispatch by HTTP Methods'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst::Test: '0'
  HTTP::Request::Common: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-ActionRole-Methods
requires:
  Catalyst: '5.90060'
  Moose::Role: '2.0602'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-ActionRole-Methods/issues
  homepage: https://github.com/jjn1056/Catalyst-ActionRole-Methods
  repository: https://github.com/jjn1056/Catalyst-ActionRole-Methods.git
version: '0.001'
